// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_integracao_ocorrencia.Utils;

namespace exe7_8_9.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191016044551_Entrevista")]
    partial class Entrevista
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("exe7_8_9.Models.Candidato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("candidato");
                });

            modelBuilder.Entity("exe7_8_9.Models.CandidatoSkil", b =>
                {
                    b.Property<int>("candidatoId");

                    b.Property<int>("skilId");

                    b.HasKey("candidatoId", "skilId");

                    b.HasIndex("skilId");

                    b.ToTable("CandidatoSkil");
                });

            modelBuilder.Entity("exe7_8_9.Models.Entrevista", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data");

                    b.Property<int>("vagaId");

                    b.HasKey("id");

                    b.HasIndex("vagaId");

                    b.ToTable("entrevista");
                });

            modelBuilder.Entity("exe7_8_9.Models.EntrevistaSkil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("entrevistaId");

                    b.Property<int>("pontuacao");

                    b.Property<int>("skilId");

                    b.HasKey("id");

                    b.HasIndex("entrevistaId");

                    b.HasIndex("skilId");

                    b.ToTable("entrevistaSkil");
                });

            modelBuilder.Entity("exe7_8_9.Models.Skil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("skil");
                });

            modelBuilder.Entity("exe7_8_9.Models.Vaga", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("vaga");
                });

            modelBuilder.Entity("exe7_8_9.Models.VagaSkil", b =>
                {
                    b.Property<int>("vagaId");

                    b.Property<int>("skilId");

                    b.HasKey("vagaId", "skilId");

                    b.HasIndex("skilId");

                    b.ToTable("VagaSkil");
                });

            modelBuilder.Entity("exe7_8_9.Models.CandidatoSkil", b =>
                {
                    b.HasOne("exe7_8_9.Models.Candidato", "candidato")
                        .WithMany("candidatoSkil")
                        .HasForeignKey("candidatoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("exe7_8_9.Models.Skil", "skil")
                        .WithMany()
                        .HasForeignKey("skilId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("exe7_8_9.Models.Entrevista", b =>
                {
                    b.HasOne("exe7_8_9.Models.Vaga", "vaga")
                        .WithMany()
                        .HasForeignKey("vagaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("exe7_8_9.Models.EntrevistaSkil", b =>
                {
                    b.HasOne("exe7_8_9.Models.Entrevista", "entrevista")
                        .WithMany("entrevistaSkil")
                        .HasForeignKey("entrevistaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("exe7_8_9.Models.Skil", "skil")
                        .WithMany()
                        .HasForeignKey("skilId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("exe7_8_9.Models.VagaSkil", b =>
                {
                    b.HasOne("exe7_8_9.Models.Skil", "skil")
                        .WithMany()
                        .HasForeignKey("skilId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("exe7_8_9.Models.Vaga", "vaga")
                        .WithMany("vagaSkils")
                        .HasForeignKey("vagaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
